In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import f1_score

import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras

GT_RAW = "./../data/Задача 1. Датасет 1. Тренировочный неразмеченный.xlsx" # это файл с датасетом, который предоставлен участникам
GT_FILTERED = "./../data/Задача 1. Датасет 1. Тренировочный размеченный.xlsx" # это датасет, из которого эксперты отфильтровали строки
#SUBM_PATH = "./nikita/turbo_pred_1.csv" # это файл участников, датасет из которого они отфильтровали строки

def metric(y_true, y_pred):
    return f1_score(y_true, y_pred)

def prepare_df(path):
    df = pd.read_excel(path)
    df["Параметр"] = pd.to_datetime(df["Параметр"])
    df.set_index("Параметр", inplace=True)
    return df

2022-11-15 17:23:03.212363: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-15 17:23:07.056717: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-11-15 17:23:08.309508: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-11-15 17:23:20.944451: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvrtc.so.11.0: cannot open shared object file: No such file or directory
2022-11-15 17:23:20.946717: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvrtc.so.11.0: cannot open shared object file: No such file or directory
2022-11-15 17:23:20.946730: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.

In [2]:
gt_raw = prepare_df(GT_RAW)
gt_filtered = prepare_df(GT_FILTERED)
#subm_df = prepare_df(SUBM_PATH)

y_gt_raw = pd.DataFrame();
gt_raw["label_true"] = 1 # 1, значит строка должна быть удалена
gt_raw["label_pred"] = 1
gt_raw.loc[gt_filtered.index, "label_true"] = 0 # 0, эти строки остаются
#gt_raw.loc[subm_df.index, "label_pred"] = 0

true = gt_raw["label_true"]
pred = gt_raw["label_pred"]

metric(true, pred)

0.027626644128677828

In [3]:
y_gt_raw = gt_raw['label_true']

y_gt_raw

Параметр
2021-03-24 13:30:00    1
2021-03-24 13:40:00    1
2021-03-24 13:50:00    0
2021-03-24 14:00:00    0
2021-03-24 14:10:00    0
                      ..
2022-03-22 04:20:00    0
2022-03-22 04:30:00    0
2022-03-22 04:40:00    0
2022-03-22 04:50:00    0
2022-03-22 05:00:00    0
Name: label_true, Length: 37339, dtype: int64

In [4]:
gt_raw

,х001,х002,х005,х006,х007,х008,х009,х010,х011,х012,...,х041,х042,х043,х044,х045,х046,х047,х048,label_true,label_pred
Параметр,,,,,,,,,,,,,,,,,,,,,
2021-03-24 13:30:00,554.01,546.45,568.66,553.95,550.21,549.53,564.10,564.59,555.75,553.00,...,531.89,533.32,564.66,554.75,539.90,537.91,562.42,566.70,1,1
2021-03-24 13:40:00,566.22,557.23,583.57,567.53,564.84,560.93,580.80,580.53,570.74,563.59,...,547.08,547.60,578.51,572.07,553.96,550.94,571.90,578.61,1,1
2021-03-24 13:50:00,577.64,566.55,590.45,576.19,573.11,571.31,590.91,589.67,579.19,569.13,...,556.89,555.97,585.74,581.30,561.09,560.34,577.21,577.46,0,1
2021-03-24 14:00:00,586.00,572.80,599.18,585.74,580.65,578.99,596.22,597.53,585.06,574.26,...,565.92,564.06,589.19,591.20,569.13,568.94,581.37,585.81,0,1
2021-03-24 14:10:00,588.59,573.98,600.51,590.21,583.39,582.58,594.09,594.99,586.70,571.53,...,569.60,567.60,584.83,595.38,572.04,571.79,583.09,588.49,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-03-22 04:20:00,555.43,560.10,557.04,548.81,548.94,580.45,582.69,578.78,577.81,579.95,...,572.80,566.38,556.54,548.89,548.70,559.06,554.61,554.63,0,1
2022-03-22 04:30:00,555.73,560.57,557.38,549.22,548.94,580.79,582.94,579.22,577.80,579.90,...,572.74,566.63,556.50,548.96,548.78,559.15,554.48,554.70,0,1
2022-03-22 04:40:00,556.68,561.24,558.31,550.17,550.21,581.46,583.78,580.09,578.74,580.90,...,574.24,567.80,557.73,550.05,549.69,560.07,555.28,555.60,0,1
2022-03-22 04:50:00,557.01,561.60,558.69,550.39,550.55,582.10,584.34,580.38,579.36,580.90,...,574.47,567.83,558.11,550.28,550.63,560.60,555.85,556.77,0,1
2022-03-22 05:00:00,556.92,561.63,558.43,550.30,550.45,582.01,584.46,580.55,579.20,580.97,...,574.29,568.13,558.23,550.56,550.33,560.54,555.75,555.73,0,1

In [5]:
gt_filtered

,х001,х002,х005,х006,х007,х008,х009,х010,х011,х012,...,х039,х040,х041,х042,х043,х044,х045,х046,х047,х048
Параметр,,,,,,,,,,,,,,,,,,,,,
2021-03-24 13:50:00,577.64,566.55,590.45,576.19,573.11,571.31,590.91,589.67,579.19,569.13,...,577.83,560.46,556.89,555.97,585.74,581.30,561.09,560.34,577.21,577.46
2021-03-24 14:00:00,586.00,572.80,599.18,585.74,580.65,578.99,596.22,597.53,585.06,574.26,...,591.73,569.11,565.92,564.06,589.19,591.20,569.13,568.94,581.37,585.81
2021-03-24 14:10:00,588.59,573.98,600.51,590.21,583.39,582.58,594.09,594.99,586.70,571.53,...,597.62,573.98,569.60,567.60,584.83,595.38,572.04,571.79,583.09,588.49
2021-03-24 14:20:00,587.23,571.40,598.82,587.36,580.06,580.23,594.21,597.14,585.66,568.78,...,597.69,572.62,567.39,565.40,579.10,594.22,570.47,569.53,581.08,586.16
2021-03-24 14:40:00,581.77,567.11,590.27,589.80,576.80,578.28,594.90,592.67,592.07,569.48,...,594.85,575.68,567.37,565.45,567.65,596.42,570.58,569.33,581.41,583.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-03-22 04:20:00,555.43,560.10,557.04,548.81,548.94,580.45,582.69,578.78,577.81,579.95,...,570.41,575.21,572.80,566.38,556.54,548.89,548.70,559.06,554.61,554.63
2022-03-22 04:30:00,555.73,560.57,557.38,549.22,548.94,580.79,582.94,579.22,577.80,579.90,...,570.91,575.23,572.74,566.63,556.50,548.96,548.78,559.15,554.48,554.70
2022-03-22 04:40:00,556.68,561.24,558.31,550.17,550.21,581.46,583.78,580.09,578.74,580.90,...,571.56,576.18,574.24,567.80,557.73,550.05,549.69,560.07,555.28,555.60
2022-03-22 04:50:00,557.01,561.60,558.69,550.39,550.55,582.10,584.34,580.38,579.36,580.90,...,572.15,576.67,574.47,567.83,558.11,550.28,550.63,560.60,555.85,556.77
2022-03-22 05:00:00,556.92,561.63,558.43,550.30,550.45,582.01,584.46,580.55,579.20,580.97,...,572.05,577.10,574.29,568.13,558.23,550.56,550.33,560.54,555.75,555.73

In [6]:
gt_raw.drop(["label_true", "label_pred"], axis = 1, inplace = True)

In [7]:
gt_raw.describe().transpose()[['mean', 'std']]

              mean           std
х001  5.657179e+02  1.083392e+01
х002  1.446599e+06  2.794209e+08
х005  5.704203e+02  2.141087e+01
х006  5.667464e+02  3.370408e+01
х007  5.693633e+02  2.479516e+01
х008 -8.516564e+26  1.645681e+29
х009  5.900476e+02  2.871668e+01
х010 -8.864726e+26  1.712958e+29
х011  5.867132e+02  1.685784e+01
х012  5.882019e+02  1.220298e+01
х013  5.839779e+02  2.300399e+01
х014  5.835302e+02  2.560954e+01
х015  5.776191e+02  3.050138e+01
х016  5.806439e+02  1.291196e+01
х017  2.043614e+06  3.947822e+08
х018  5.756700e+02  1.363426e+01
х019  5.684472e+02  3.192700e+01
х020  5.608968e+02  3.132402e+01
х021  5.602229e+02  1.464487e+01
х022  5.665461e+02  3.314138e+01
х023 -7.847023e+26  1.516304e+29
х024 -7.016792e+26  1.355876e+29
х025 -4.285064e+26  8.280158e+28
х026  5.683767e+02  2.382398e+01
х029 -2.212164e+26  4.274632e+28
х030  5.664145e+02  3.413923e+01
х031  5.703764e+02  2.452361e+01
х032  5.872855e+02  1.089053e+01
х033  5.913811e+02  1.593030e+01
х034  5.887938e+02  1.398728e+01
х035  5.861314e+02  2.279768e+01
х036  9.973983e+05  1.926167e+08
х037  5.851635e+02  1.274360e+01
х038  1.470797e+06  2.840935e+08
х039  2.612025e+06  5.046176e+08
х040  5.798316e+02  3.023162e+01
х041  5.764509e+02  3.506882e+01
х042  5.753708e+02  1.451498e+01
х043  5.699402e+02  1.890597e+01
х044  5.630220e+02  1.764359e+01
х045  5.603381e+02  1.807497e+01
х046  5.671122e+02  2.455817e+01
х047  5.696268e+02  1.430621e+01
х048  5.680196e+02  2.759858e+01

In [8]:
normalizer = tf.keras.layers.Normalization(axis=-1)
normalizer.adapt(np.array(gt_raw))

2022-11-15 17:26:39.129602: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-11-15 17:26:39.172980: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-11-15 17:26:39.173970: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-11-15 17:26:39.184693: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-15 17:26:39.186196: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-11-15 17:26:39.186458: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-11-15 17:26:39.186766: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-11-15 17:26:44.170858: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-11-15 17:26:44.178859: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-11-15 17:26:44.178879: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1700] Could not identify NUMA node of platform GPU id 0, defaulting to 0.  Your kernel may not have been built with NUMA support.
2022-11-15 17:26:44.179105: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-11-15 17:26:44.185437: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9565 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060, pci bus id: 0000:01:00.0, compute capability: 8.6

In [9]:
print(normalizer.mean.numpy())

[[ 5.6571686e+02  1.4465958e+06  5.7042047e+02  5.6674548e+02
   5.6936334e+02 -8.5165600e+26  5.9004785e+02 -8.8647231e+26
   5.8671228e+02  5.8820135e+02  5.8397852e+02  5.8353021e+02
   5.7761810e+02  5.8064368e+02  2.0436056e+06  5.7566962e+02
   5.6844647e+02  5.6089618e+02  5.6022247e+02  5.6654706e+02
  -7.8470199e+26 -7.0167880e+26 -4.2850632e+26  5.6837653e+02
  -2.2121638e+26  5.6641455e+02  5.7037634e+02  5.8728589e+02
   5.9138074e+02  5.8879346e+02  5.8613141e+02  9.9739756e+05
   5.8516296e+02  1.4707931e+06  2.6120300e+06  5.7983142e+02
   5.7645166e+02  5.7537097e+02  5.6993951e+02  5.6302216e+02
   5.6033801e+02  5.6711133e+02  5.6962677e+02  5.6801898e+02]]

In [10]:
keras_1_model = tf.keras.Sequential([
    normalizer,
    tf.keras.layers.Dense(units=10),
    tf.keras.layers.Dense(units=1, activation='sigmoid')
])

In [11]:
keras_1_model.compile(
    optimizer= keras.optimizers.Adam(learning_rate=0.1),
    loss='binary_crossentropy',
    metrics=['accuracy'])

In [12]:
%%time
history = keras_1_model.fit(
    gt_raw,
    y_gt_raw,
    epochs=10,
    # Suppress logging.
    verbose=0,
    # Calculate validation results on 20% of the training data.
    validation_split = 0.2)

2022-11-15 17:27:18.638630: I tensorflow/stream_executor/cuda/cuda_blas.cc:1614] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.

CPU times: user 46.3 s, sys: 24.7 s, total: 1min 11s
Wall time: 42 s

In [13]:
hist = pd.DataFrame(history.history)
hist['epoch'] = history.epoch
hist

       loss  accuracy  val_loss  val_accuracy  epoch
0  0.111072  0.983964  0.025579      0.994912      0
1  0.050610  0.989856  0.027266      0.989555      1
2  0.223977  0.985672  0.340605      0.994510      2
3  0.090301  0.988551  0.023718      0.995179      3
4  0.068808  0.988752  0.021764      0.995447      4
5  0.050886  0.989522  0.030319      0.992367      5
6  0.362178  0.985237  0.025892      0.995447      6
7  0.053320  0.990057  0.023402      0.994242      7
8  0.052538  0.989622  0.022380      0.994510      8
9  0.058042  0.988852  0.040213      0.990627      9

In [14]:
GT_RAW_2 = "./Data2RAW.xlsx" # это файл с датасетом, который предоставлен участникам
GT_FILTERED_2 = "./Data2FILTERED.xlsx" # это датасет, из которого эксперты отфильтровали строки

In [15]:
gt_raw_2 = prepare_df(GT_RAW_2)
gt_filtered_2 = prepare_df(GT_FILTERED_2)
#subm_df = prepare_df(SUBM_PATH)

y_gt_raw_2 = pd.DataFrame();
gt_raw_2["label_true"] = 1 # 1, значит строка должна быть удалена
gt_raw_2["label_pred"] = 1
gt_raw_2.loc[gt_filtered_2.index, "label_true"] = 0 # 0, эти строки остаются
#gt_raw.loc[subm_df.index, "label_pred"] = 0

FileNotFoundError: [Errno 2] No such file or directory: './Data2RAW.xlsx'

In [16]:
y_gt_raw_2 = gt_raw_2['label_true']
gt_raw_2.drop(["label_true", "label_pred"], axis = 1, inplace = True)

In [17]:
gt_raw_2

,х001,х002,х005,х006,х007,х008,х009,х010,х011,х012,...,х039,х040,х041,х042,х043,х044,х045,х046,х047,х048
Параметр,,,,,,,,,,,,,,,,,,,,,
2021-01-01 00:00:00,573.5,573.70000,563.20000,563.5,584.8,585.7,570.9,570.6,563.4,563.3,...,572.4,572.4,568.4,568.2,578.1,580.4,575.7,576.2,585.5,585.9
2021-01-01 00:10:00,573.5,573.70000,563.20000,563.5,584.8,585.7,570.9,570.6,563.4,563.3,...,572.4,572.4,568.4,568.2,578.1,580.4,575.7,576.2,585.5,585.9
2021-01-01 00:20:00,574.2,574.30000,563.10004,564.2,585.8,586.4,570.6,569.9,564.5,564.6,...,572.4,572.9,568.4,568.0,579.0,580.3,575.6,575.5,587.3,586.7
2021-01-01 00:30:00,572.9,573.50000,562.80000,563.4,586.2,586.8,570.6,569.7,565.6,565.3,...,572.5,572.8,568.4,568.3,579.0,580.1,574.6,575.7,586.4,585.7
2021-01-01 00:40:00,573.9,574.40000,563.10004,564.2,585.8,586.1,570.2,569.8,564.6,564.2,...,572.2,572.4,568.1,568.2,578.9,580.1,574.9,575.9,587.3,586.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-29 13:00:00,559.5,560.00000,563.90000,564.5,580.7,581.0,580.2,580.2,576.9,577.3,...,548.4,548.5,544.5,543.9,553.5,553.6,548.8,549.0,554.5,553.9
2021-12-29 13:10:00,559.4,560.10004,564.10004,564.2,580.9,580.7,580.5,580.0,576.7,577.4,...,548.7,549.4,544.4,544.3,553.7,554.4,549.0,549.2,554.4,554.1
2021-12-29 13:20:00,559.7,560.50000,562.60004,564.0,580.4,581.0,580.4,580.5,576.8,577.7,...,548.6,549.0,543.6,544.3,553.9,553.6,548.8,549.1,554.1,554.2
2021-12-29 13:30:00,560.2,560.70000,563.80000,564.4,580.9,580.9,580.2,580.2,576.9,577.4,...,548.3,549.0,544.3,544.3,553.7,554.0,549.3,549.3,555.0,554.3
2021-12-29 13:40:00,560.4,561.00000,565.00000,565.7,581.2,581.3,580.7,580.6,577.5,578.3,...,548.6,549.5,545.2,544.4,554.8,554.6,549.3,549.9,555.0,554.8

In [18]:
%%time
result = keras_1_model.predict(
    gt_raw_2
    )

1342/1342 [==============================] - 1s 740us/step
CPU times: total: 11.2 s
Wall time: 1.42 s

In [19]:
result

array([[1.4469815e-16],
       [1.4469815e-16],
       [6.2546116e-18],
       ...,
       [3.4276258e-02],
       [2.5778577e-02],
       [4.1827802e-03]], dtype=float32)

In [20]:
for num in range(len(result)):
    if result[num] >= 0.5:
        result[num] = 1
    else:
        result[num] = 0

In [21]:

true = y_gt_raw_2
pred = result
metric(true, pred)

0.07326283987915408

In [22]:
result = result.astype('int64')
result

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [23]:
y_gt_raw_2

Параметр
2021-01-01 00:00:00    0
2021-01-01 00:10:00    0
2021-01-01 00:20:00    0
2021-01-01 00:30:00    0
2021-01-01 00:40:00    0
                      ..
2021-12-29 13:00:00    1
2021-12-29 13:10:00    1
2021-12-29 13:20:00    1
2021-12-29 13:30:00    1
2021-12-29 13:40:00    0
Name: label_true, Length: 42932, dtype: int64

In [24]:
y = y_gt_raw_2.to_numpy()
y

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [25]:
flag = 0
for n in range(len(result)):
    if result[n] != y[n]:
        flag = flag + 1

In [26]:
flag

2454

In [27]:
flag2 = 0
for n in range(len(y)):
    if y[n] == 1:
        flag2 = flag2 + 1

In [28]:
flag2

1772

In [29]:
result2 = keras_1_model.predict(
    gt_raw
    )

1167/1167 [==============================] - 1s 758us/step

In [30]:
result2

array([[9.9961692e-01],
       [1.6040259e-04],
       [1.4284853e-03],
       ...,
       [2.0661680e-13],
       [1.2133824e-13],
       [1.7680558e-13]], dtype=float32)

In [31]:
from sklearn.ensemble import RandomForestClassifier

In [32]:
rf = RandomForestClassifier()

In [33]:
rf.fit(gt_raw, y_gt_raw)
y_train = rf.predict(gt_raw)
y_test = rf.predict(gt_raw_2)

In [34]:
true = y_gt_raw
pred = y_train
metric(true, pred)

1.0

In [35]:
true = y_gt_raw_2
pred = y_test
metric(true, pred)

0.12157142321113654